export default {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    CLEAR_PRODUCT_DETAILS: 'CLEAR_PRODUCT_DETAILS',
    GET_ACTIVE_CART: 'GET_ACTIVE_CART',
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_CART_TOTALS: 'GET_CART_TOTALS',
    GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
    GET_SCHEDULE: 'GET_SCHEDULE'
}